name: Build PDFtoExcel

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      
      - name: Download and Install Tesseract portable
        run: |
          # 1. Создаем папку внутри репозитория для переносимой версии
          mkdir tesseract_portable
          
          # 2. Устанавливаем Tesseract скрытно прямо в созданную папку
          winget install --id UB-Mannheim.TesseractOCR --silent --accept-source-agreements --accept-package-agreements --location "D:\a\PDFtoExcel\PDFtoExcel\tesseract_portable"
          
          # 3. Проверяем, что исполняемый файл появился в нужной директории
          dir tesseract_portable
        shell: powershell
      
      - name: Download Poppler portable
        run: |
          # Скачиваем и распаковываем в папку poppler_portable
          curl -L -o poppler.zip https://github.com/oschwartz10612/poppler-windows/releases/download/v24.08.0-0/Release-24.08.0-0.zip
          mkdir poppler_portable
          7z x poppler.zip -opoppler_portable -y
      
      - name: Build EXE
        run: |
          pyinstaller --onefile --name PDFtoExcel --add-data "tesseract_portable;tesseract_portable" --add-data "poppler_portable;poppler_portable" main.py
      
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: PDFtoExcel
          path: dist/PDFtoExcel.exe
